<?php
require 'config_labour.php'; // Connect to database

if (!isset($_GET['id']) || empty($_GET['id'])) {
    die("Invalid Report ID.");
}

$report_id = intval($_GET['id']);

try {
    // Fetch report details
    $stmt = $pdo->prepare("SELECT * FROM reports WHERE id = ?");
    $stmt->execute([$report_id]);
    $report = $stmt->fetch(PDO::FETCH_ASSOC);

    if (!$report) {
        die("Report not found.");
    }

} catch (PDOException $e) {
    die("Database error: " . $e->getMessage());
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Report Details - <?php echo htmlspecialchars($report['report_name']); ?></title>
    <link rel="stylesheet" href="style_V.css">
</head>
<body>

<h2>Report Details</h2>
<!-- <p><strong>Report Name:</strong> <?php echo htmlspecialchars($report['report_name']); ?></p> -->
<p><strong>Department:</strong> <?php echo htmlspecialchars($report['department']); ?></p>
<p><strong>Generated On:</strong> <?php echo htmlspecialchars($report['generated_on']); ?></p>
<p><strong>Generated By:</strong> <?php echo htmlspecialchars($report['generated_by']); ?></p>
<p><strong>Type:</strong> <?php echo htmlspecialchars($report['type']); ?></p>
<p><strong>Type Class:</strong> <span class="badge bg-<?php echo htmlspecialchars($report['type_class']); ?>">
    <?php echo htmlspecialchars($report['type']); ?></span></p>

<a href="labour.php">Back to Dashboard</a>

</body>
</html>
